### ISSUE TITLE
Negative Heavy Operations

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#313]
With the 4.1 TMA update, negative heavy operations Can be seen on Skylake best micro architectures. 
Toplev Correctly points to a missing event: Uops_Retired.Macro_Fused. 
Running event_download.py doesn’t really solve the problem since the event is still missing 01.org.

**Comment by andikleen** [comment]
yes have to wait for the eventlist update. hopefully it happens soon.
there is also another problem with some uncore eventa generating bad
groups

**Comment by aayasin** [comment]
I verified the negative Heavy Operation was resolved on SKL client. 

Keep this entry open for the Uncore issue.

**Comment by andikleen** [comment]
The uncore issue should be already fixed.

**Comment by andikleen** [comment]
Actually the problem is not fully fixed yet because SKX and CLX event lists are still missing the event.

**Comment by andikleen** [comment]
Event lists should be ok on SKX/CLX
